
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.conn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class MasterCustomer extends javax.swing.JInternalFrame {

    /**
     * Creates new form MasterCustomer
     */
    public MasterCustomer() {
        initComponents();
        kosongkan();
    }
    
     public void kosongkan(){
        txtkodecustomer.setText("");
        txtnamacustomer.setText("");
        txtalamat.setText("");
        txttelepon.setText("");
        txtfax.setText("");
        txtemail.setText("");
        txtcontact.setText("");
        txtcaridata.setText("");
        txtkodecustomer.requestFocus();
        tampilgrid();
    }
     
     public void databaru(){
        txtnamacustomer.setText("");
        txtalamat.setText("");
        txttelepon.setText("");
        txtfax.setText("");
        txtemail.setText("");
        txtcontact.setText("");
        txtcaridata.setText("");
        txtnamacustomer.requestFocus();
    }
     
     public void ketemu(){
        try{
              Connection c = conn.getKoneksi();
              Statement s = c.createStatement();
              String sql = "select * from tblcustomer where kode_customer='"+txtkodecustomer.getText()+"'";
              ResultSet res = s.executeQuery(sql);
              while(res.next()){
              txtnamacustomer.setText(res.getString("nama_customer"));
              txtalamat.setText(res.getString("alamat_customer"));
              txttelepon.setText(res.getString("telepon_customer"));
              txtfax.setText(res.getString("fax_customer"));
              txtemail.setText(res.getString("email_customer"));
              txtcontact.setText(res.getString("person_customer"));
              txtnamacustomer.requestFocus();}
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);
            
        }
    }
     
     public void tampilgrid(){
        Object header[]={"Kode Customer","Nama Customer","Alamat Customer","Telepon Customer","Fax Customer","Email Customer","Contact Customer"};
        DefaultTableModel data = new DefaultTableModel(null, header);
        dgv.setModel(data);
        try{
            Connection c = conn.getKoneksi();
            Statement s = c.createStatement();
            String sql = "select * from tblcustomer";
            ResultSet res = s.executeQuery(sql);
            while(res.next()){
                String kolom1 = res.getString("kode_customer");
                String kolom2 = res.getString("nama_customer");
                String kolom3 = res.getString("alamat_customer");
                String kolom4 = res.getString("telepon_customer");
                String kolom5 = res.getString("fax_customer");
                String kolom6 = res.getString("email_customer");
                String kolom7 = res.getString("person_customer");
                
                String kolom[] = {kolom1, kolom2, kolom3, kolom4, kolom5, kolom6, kolom7};
                data.addRow(kolom);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, e);
        }               
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtkodecustomer = new javax.swing.JTextField();
        txtnamacustomer = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txttelepon = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtcontact = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtfax = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnsimpan = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        btntutup = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtcaridata = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        dgv = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Master Customer");
        setPreferredSize(new java.awt.Dimension(462, 420));

        jLabel1.setText("Kode");

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        jLabel4.setText("Telepon");

        jLabel5.setText("Email");

        jLabel6.setText("Contact Person");

        txtkodecustomer.setPreferredSize(new java.awt.Dimension(121, 20));
        txtkodecustomer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtkodecustomerFocusLost(evt);
            }
        });
        txtkodecustomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtkodecustomerKeyTyped(evt);
            }
        });

        txtnamacustomer.setPreferredSize(new java.awt.Dimension(121, 20));

        txtalamat.setPreferredSize(new java.awt.Dimension(121, 20));

        txttelepon.setPreferredSize(new java.awt.Dimension(121, 20));

        txtemail.setPreferredSize(new java.awt.Dimension(121, 20));

        txtcontact.setPreferredSize(new java.awt.Dimension(121, 20));

        jLabel7.setText("Fax");

        txtfax.setPreferredSize(new java.awt.Dimension(121, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnamacustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtalamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtkodecustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcontact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(191, 191, 191))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtkodecustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnamacustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfax, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MasterSupplier/btnsimpan.Image.png"))); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsimpan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MasterSupplier/btnhapus.Image.png"))); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnhapus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MasterSupplier/btnbatal.Image.png"))); // NOI18N
        btnbatal.setText("Batal");
        btnbatal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbatal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        btntutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MasterSupplier/btntutup.Image.png"))); // NOI18N
        btntutup.setText("Tutup");
        btntutup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btntutup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btntutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntutupActionPerformed(evt);
            }
        });

        txtcaridata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcaridataKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtcaridata);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntutup, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btntutup, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        dgv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dgv.setPreferredSize(new java.awt.Dimension(446, 150));
        dgv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dgvMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dgv);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
       kosongkan();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btntutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntutupActionPerformed
        this.dispose();
    }//GEN-LAST:event_btntutupActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        try{
                Connection c = conn.getKoneksi();
                Statement s = c.createStatement();
                String sql = "select * from tblcustomer where kode_customer= '"+txtkodecustomer.getText()+"'";
                ResultSet res = s.executeQuery(sql);
                if(res.next()){
                    String edit  = "update tblcustomer set nama_customer = '"+txtnamacustomer.getText()+"',alamat_customer = '"+txtalamat.getText()+"',telepon_customer = '"+txttelepon.getText()+"',fax_customer = '"+txtfax.getText()+"',email_customer = '"+txtemail.getText()+"',person_customer = '"+txtcontact.getText()+"'where kode_customer = '"+txtkodecustomer.getText()+"'";
                    PreparedStatement st=c.prepareStatement(edit);
                    st.execute();
                }else{
                    String simpan  = "insert into tblcustomer values('" +txtkodecustomer.getText()+ "','" +txtnamacustomer.getText()+ "','" +txtalamat.getText()+ "','"+txttelepon.getText()+"','"+txtfax.getText()+"','"+txtemail.getText()+"','"+txtcontact.getText()+"')";
                    PreparedStatement st=c.prepareStatement(simpan);
                    st.execute();
                }
                
            }catch(SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);
                
            }
            kosongkan();
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void dgvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dgvMouseClicked
        int row = dgv.rowAtPoint(evt.getPoint());
        String kode_customer = dgv.getValueAt(row, 0).toString();
        String nama_customer = dgv.getValueAt(row, 1).toString();
        String alamat_customer = dgv.getValueAt(row, 2).toString();
        String telepon_customer = dgv.getValueAt(row, 3).toString();
        String fax_customer = dgv.getValueAt(row, 4).toString();
        String email_customer = dgv.getValueAt(row, 5).toString();
        String person_customer = dgv.getValueAt(row, 6).toString();
        
        txtkodecustomer.setText(String.valueOf(kode_customer));
        txtnamacustomer.setText(String.valueOf(nama_customer));
        txtalamat.setText(String.valueOf(alamat_customer));
        txttelepon.setText(String.valueOf(telepon_customer));
        txtfax.setText(String.valueOf(fax_customer));
        txtemail.setText(String.valueOf(email_customer));
        txtcontact.setText(String.valueOf(person_customer));
    }//GEN-LAST:event_dgvMouseClicked

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
         if(txtkodecustomer.getText()== ""){
           JOptionPane.showMessageDialog(rootPane, "Kode Customer Harus diisi");
           txtkodecustomer.requestFocus();
       }
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Yakin Ingin dihapus..?", "Warning", dialogButton);
            if(dialogResult == 0) {
               try{
                Connection c = conn.getKoneksi();
                Statement s = c.createStatement();
                String hapus = "delete * from tblcustomer where kode_customer= '"+txtkodecustomer.getText()+"'";
                PreparedStatement st=c.prepareStatement(hapus);
                st.execute();
                kosongkan();
                }catch(SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);              
                }
            } else {
                kosongkan();
}    
    }//GEN-LAST:event_btnhapusActionPerformed

    private void txtkodecustomerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtkodecustomerFocusLost
        try{
                Connection c = conn.getKoneksi();
                Statement s = c.createStatement();
                String sql = "select * from tblcustomer where kode_customer= '"+txtkodecustomer.getText()+"'";
                ResultSet res = s.executeQuery(sql);
                if(res.next()){
                    ketemu();
                }else{
                    databaru();
                }}catch(SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);              
                }
               ketemu();
    }//GEN-LAST:event_txtkodecustomerFocusLost

    private void txtcaridataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcaridataKeyPressed
        Object header[]={"Kode Customer","Nama Customer","Alamat Customer","Telepon Customer","Fax Customer","Email Customer","Contact Customer"};
        DefaultTableModel data = new DefaultTableModel(null, header);
        dgv.setModel(data);
        try{
            Connection c = conn.getKoneksi();
            Statement s = c.createStatement();
            String sql = "select * from tblcustomer where nama_customer like '%"+txtcaridata.getText()+"%'";
            ResultSet res = s.executeQuery(sql);
            while(res.next()){
                String kolom1 = res.getString("kode_customer");
                String kolom2 = res.getString("nama_customer");
                String kolom3 = res.getString("alamat_customer");
                String kolom4 = res.getString("telepon_customer");
                String kolom5 = res.getString("fax_customer");
                String kolom6 = res.getString("email_customer");
                String kolom7 = res.getString("contact_customer");
                
                String kolom[] = {kolom1, kolom2, kolom3, kolom4, kolom5, kolom6, kolom7};
                data.addRow(kolom);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_txtcaridataKeyPressed

    private void txtkodecustomerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkodecustomerKeyTyped
         evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_txtkodecustomerKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntutup;
    private javax.swing.JTable dgv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextPane txtcaridata;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfax;
    private javax.swing.JTextField txtkodecustomer;
    private javax.swing.JTextField txtnamacustomer;
    private javax.swing.JTextField txttelepon;
    // End of variables declaration//GEN-END:variables
}
