
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JMenuItem;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class MenuUtama extends javax.swing.JFrame {
    
    public JLabel txtkodeuser(){
        return this.TXTkodeuser;
    }
    
    public JLabel txtnamauser(){
        return TXTnamauser;
    }
    
    public JLabel txtstatususer(){
        return TXTstatususer;
    }
    
    public JMenuItem btnuser(){
        return btnuser;
    }
 

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TXTkodeuser = new javax.swing.JLabel();
        TXTnamauser = new javax.swing.JLabel();
        TXTstatususer = new javax.swing.JLabel();
        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnuser = new javax.swing.JMenuItem();
        btnbarang = new javax.swing.JMenuItem();
        btnperkiraan = new javax.swing.JMenuItem();
        btnsupplier = new javax.swing.JMenuItem();
        btncustomer = new javax.swing.JMenuItem();
        btnprofil = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btntpembelian = new javax.swing.JMenuItem();
        btnreturbeli = new javax.swing.JMenuItem();
        btntpenjualan = new javax.swing.JMenuItem();
        btnreturjual = new javax.swing.JMenuItem();
        btnbyrutang = new javax.swing.JMenuItem();
        btntrmpiutang = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btnlkeuangan = new javax.swing.JMenuItem();
        btnlpembelian = new javax.swing.JMenuItem();
        btnlreturbeli = new javax.swing.JMenuItem();
        btnlpenjualan = new javax.swing.JMenuItem();
        btnlreturjual = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        btnlogoff = new javax.swing.JMenuItem();
        btnexit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Jual Beli");
        setBackground(new java.awt.Color(51, 0, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(MAXIMIZED_BOTH);
        setSize(new java.awt.Dimension(1280, 720));

        TXTkodeuser.setText("jLabel1");
        TXTkodeuser.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        TXTnamauser.setText("jLabel1");
        TXTnamauser.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        TXTstatususer.setText("jLabel1");
        TXTstatususer.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );

        jMenu1.setText("Master Data");
        jMenu1.setNextFocusableComponent(jMenu1);

        btnuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MenuUtama/btnuser.Image.png"))); // NOI18N
        btnuser.setText("User");
        btnuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuserActionPerformed(evt);
            }
        });
        jMenu1.add(btnuser);

        btnbarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MenuUtama/btnbarang.Image.png"))); // NOI18N
        btnbarang.setText("Barang");
        btnbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbarangActionPerformed(evt);
            }
        });
        jMenu1.add(btnbarang);

        btnperkiraan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MenuUtama/btnperkiraan.Image.png"))); // NOI18N
        btnperkiraan.setText("Perkiraan");
        btnperkiraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnperkiraanActionPerformed(evt);
            }
        });
        jMenu1.add(btnperkiraan);

        btnsupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MenuUtama/btnsupplier.Image.png"))); // NOI18N
        btnsupplier.setText("Supplier");
        btnsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupplierActionPerformed(evt);
            }
        });
        jMenu1.add(btnsupplier);

        btncustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MenuUtama/btncustomer.Image.png"))); // NOI18N
        btncustomer.setText("Customer");
        btncustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncustomerActionPerformed(evt);
            }
        });
        jMenu1.add(btncustomer);

        btnprofil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MenuUtama/btnprofil.Image.png"))); // NOI18N
        btnprofil.setText("Profil Perusahaan");
        btnprofil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprofilActionPerformed(evt);
            }
        });
        jMenu1.add(btnprofil);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");

        btntpembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MenuUtama/btnpembelian.Image.png"))); // NOI18N
        btntpembelian.setText("Pembelian");
        btntpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntpembelianActionPerformed(evt);
            }
        });
        jMenu2.add(btntpembelian);

        btnreturbeli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MenuUtama/btnreturbeli.Image.png"))); // NOI18N
        btnreturbeli.setText("Retur Beli");
        btnreturbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturbeliActionPerformed(evt);
            }
        });
        jMenu2.add(btnreturbeli);

        btntpenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MenuUtama/btnpenjualan.Image.png"))); // NOI18N
        btntpenjualan.setText("Penjualan");
        btntpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntpenjualanActionPerformed(evt);
            }
        });
        jMenu2.add(btntpenjualan);

        btnreturjual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MenuUtama/btnreturjual.Image.png"))); // NOI18N
        btnreturjual.setText("Retur Jual");
        btnreturjual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturjualActionPerformed(evt);
            }
        });
        jMenu2.add(btnreturjual);

        btnbyrutang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MenuUtama/btnbayarutang.Image.png"))); // NOI18N
        btnbyrutang.setText("Bayar Utang");
        btnbyrutang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbyrutangActionPerformed(evt);
            }
        });
        jMenu2.add(btnbyrutang);

        btntrmpiutang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MenuUtama/btnterimapiutang.Image.png"))); // NOI18N
        btntrmpiutang.setText("Terima Piutang");
        btntrmpiutang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrmpiutangActionPerformed(evt);
            }
        });
        jMenu2.add(btntrmpiutang);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Laporan");

        btnlkeuangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MenuUtama/btnlapmaster.Image.png"))); // NOI18N
        btnlkeuangan.setText("Keuangan");
        btnlkeuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlkeuanganActionPerformed(evt);
            }
        });
        jMenu3.add(btnlkeuangan);

        btnlpembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MenuUtama/btnlappembelian.Image.png"))); // NOI18N
        btnlpembelian.setText("Pembelian");
        btnlpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlpembelianActionPerformed(evt);
            }
        });
        jMenu3.add(btnlpembelian);

        btnlreturbeli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MenuUtama/btnlapreturbeli.Image.png"))); // NOI18N
        btnlreturbeli.setText("Retur Beli");
        btnlreturbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlreturbeliActionPerformed(evt);
            }
        });
        jMenu3.add(btnlreturbeli);

        btnlpenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MenuUtama/btnlappenjualan.Image.png"))); // NOI18N
        btnlpenjualan.setText("Penjualan");
        btnlpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlpenjualanActionPerformed(evt);
            }
        });
        jMenu3.add(btnlpenjualan);

        btnlreturjual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MenuUtama/btnlapreturjual.Image.png"))); // NOI18N
        btnlreturjual.setText("Retur Jual");
        btnlreturjual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlreturjualActionPerformed(evt);
            }
        });
        jMenu3.add(btnlreturjual);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Keluar");

        btnlogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MenuUtama/btnlogoff.Image.png"))); // NOI18N
        btnlogoff.setText("Log Off");
        btnlogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoffActionPerformed(evt);
            }
        });
        jMenu4.add(btnlogoff);

        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MenuUtama/btnexit.Image.png"))); // NOI18N
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jMenu4.add(btnexit);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TXTkodeuser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTnamauser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTstatususer)
                .addContainerGap(652, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Desktop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTkodeuser)
                    .addComponent(TXTnamauser)
                    .addComponent(TXTstatususer))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuserActionPerformed
        MasterUser mUser = new MasterUser();
        Dimension desktopSize = Desktop.getSize();
        Dimension mUserSize = mUser.getSize();
        Desktop.add(mUser);
        mUser.show();
        mUser.setLocation((desktopSize.width - mUserSize.width)/2, (desktopSize.height - mUserSize.height)/2);// TODO add your handling code here:
    }//GEN-LAST:event_btnuserActionPerformed

    private void btnbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbarangActionPerformed
        MasterBarang mBarang = new MasterBarang();
        Dimension desktopSize = Desktop.getSize();
        Dimension mBarangSize = mBarang.getSize();
        Desktop.add(mBarang);
        mBarang.show();
        mBarang.setLocation((desktopSize.width - mBarangSize.width)/2, (desktopSize.height - mBarangSize.height)/2);// TODO add your handling code here:
    }//GEN-LAST:event_btnbarangActionPerformed

    private void btnlogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoffActionPerformed
        Login login = new Login();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_btnlogoffActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnperkiraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnperkiraanActionPerformed
        MasterPerkiraan mPerkiraan = new MasterPerkiraan();
        Dimension desktopSize = Desktop.getSize();
        Dimension mPerkiraanSize = mPerkiraan.getSize();
        Desktop.add(mPerkiraan);
        mPerkiraan.show();
        mPerkiraan.setLocation((desktopSize.width - mPerkiraanSize.width)/2, (desktopSize.height - mPerkiraanSize.height)/2);
    }//GEN-LAST:event_btnperkiraanActionPerformed

    private void btnsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupplierActionPerformed
         MasterSupplier mSupplier = new MasterSupplier();
        Dimension desktopSize = Desktop.getSize();
        Dimension mSupplierSize = mSupplier.getSize();
        Desktop.add(mSupplier);
        mSupplier.show();
        mSupplier.setLocation((desktopSize.width - mSupplierSize.width)/2, (desktopSize.height - mSupplierSize.height)/2);
    }//GEN-LAST:event_btnsupplierActionPerformed

    private void btncustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncustomerActionPerformed
        MasterCustomer mCustomer = new MasterCustomer();
        Dimension desktopSize = Desktop.getSize();
        Dimension mCustomerSize = mCustomer.getSize();
        Desktop.add(mCustomer);
        mCustomer.show();
        mCustomer.setLocation((desktopSize.width - mCustomerSize.width)/2, (desktopSize.height - mCustomerSize.height)/2);
    }//GEN-LAST:event_btncustomerActionPerformed

    private void btnprofilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprofilActionPerformed
        MasterProfil mProfil = new MasterProfil();
        Dimension desktopSize = Desktop.getSize();
        Dimension mProfilSize = mProfil.getSize();
        Desktop.add(mProfil);
        mProfil.show();
        mProfil.setLocation((desktopSize.width - mProfilSize.width)/2, (desktopSize.height - mProfilSize.height)/2);
    }//GEN-LAST:event_btnprofilActionPerformed

    private void btntpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntpembelianActionPerformed
        MenuUtama mUtama = new MenuUtama();
        TransaksiPembelian tPembelian = new TransaksiPembelian();
        tPembelian.TXTkode = TXTkodeuser.getText();
        Dimension desktopSize = Desktop.getSize();
        Dimension tPembelianSize = tPembelian.getSize();
        Desktop.add(tPembelian);
        tPembelian.show();
        tPembelian.setLocation((desktopSize.width - tPembelianSize.width)/2, (desktopSize.height - tPembelianSize.height)/2);
    }//GEN-LAST:event_btntpembelianActionPerformed

    private void btntpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntpenjualanActionPerformed
        MenuUtama mUtama = new MenuUtama();
        TransaksiPenjualan tPenjualan = new TransaksiPenjualan();
        tPenjualan.TXTkode = TXTkodeuser.getText();
        Dimension desktopSize = Desktop.getSize();
        Dimension tPenjualanSize = tPenjualan.getSize();
        Desktop.add(tPenjualan);
        tPenjualan.show();
        tPenjualan.setLocation((desktopSize.width - tPenjualanSize.width)/2, (desktopSize.height - tPenjualanSize.height)/2);
    }//GEN-LAST:event_btntpenjualanActionPerformed

    private void btnreturbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturbeliActionPerformed
         MenuUtama mUtama = new MenuUtama();
        TransaksiReturPembelian tReturPembelian = new TransaksiReturPembelian();
        tReturPembelian.TXTkode = TXTkodeuser.getText();
        Dimension desktopSize = Desktop.getSize();
        Dimension tReturPembelianSize = tReturPembelian.getSize();
        Desktop.add(tReturPembelian);
        tReturPembelian.show();
        tReturPembelian.setLocation((desktopSize.width - tReturPembelianSize.width)/2, (desktopSize.height - tReturPembelianSize.height)/2);
    }//GEN-LAST:event_btnreturbeliActionPerformed

    private void btnreturjualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturjualActionPerformed
          MenuUtama mUtama = new MenuUtama();
        TransaksiReturPenjualan tReturPenjualan = new TransaksiReturPenjualan();
        tReturPenjualan.TXTkode = TXTkodeuser.getText();
        Dimension desktopSize = Desktop.getSize();
        Dimension tReturPenjualanSize = tReturPenjualan.getSize();
        Desktop.add(tReturPenjualan);
        tReturPenjualan.show();
        tReturPenjualan.setLocation((desktopSize.width - tReturPenjualanSize.width)/2, (desktopSize.height - tReturPenjualanSize.height)/2);
    }//GEN-LAST:event_btnreturjualActionPerformed

    private void btnbyrutangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbyrutangActionPerformed
         MenuUtama mUtama = new MenuUtama();
        TransaksiBayarUtang tBayarUtang = new TransaksiBayarUtang();
        tBayarUtang.TXTkode = TXTkodeuser.getText();
        Dimension desktopSize = Desktop.getSize();
        Dimension tBayarUtangSize = tBayarUtang.getSize();
        Desktop.add(tBayarUtang);
        tBayarUtang.show();
        tBayarUtang.setLocation((desktopSize.width - tBayarUtangSize.width)/2, (desktopSize.height - tBayarUtangSize.height)/2);
    }//GEN-LAST:event_btnbyrutangActionPerformed

    private void btntrmpiutangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrmpiutangActionPerformed
        MenuUtama mUtama = new MenuUtama();
        TransaksiTerimaPiutang tTerimaPiutang = new TransaksiTerimaPiutang();
        tTerimaPiutang.TXTkode = TXTkodeuser.getText();
        Dimension desktopSize = Desktop.getSize();
        Dimension tTerimaPiutangSize = tTerimaPiutang.getSize();
        Desktop.add(tTerimaPiutang);
        tTerimaPiutang.show();
        tTerimaPiutang.setLocation((desktopSize.width - tTerimaPiutangSize.width)/2, (desktopSize.height - tTerimaPiutangSize.height)/2);
    }//GEN-LAST:event_btntrmpiutangActionPerformed

    private void btnlpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlpembelianActionPerformed
         MenuUtama mUtama = new MenuUtama();
        LaporanPembelian lPembelian = new LaporanPembelian();
        Dimension desktopSize = Desktop.getSize();
        Dimension lPembelianSize = lPembelian.getSize();
        Desktop.add(lPembelian);
        lPembelian.show();
        lPembelian.setLocation((desktopSize.width - lPembelianSize.width)/2, (desktopSize.height - lPembelianSize.height)/2);
    }//GEN-LAST:event_btnlpembelianActionPerformed

    private void btnlpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlpenjualanActionPerformed
            MenuUtama mUtama = new MenuUtama();
        LaporanPenjualan lPenjualan = new LaporanPenjualan();
        Dimension desktopSize = Desktop.getSize();
        Dimension lPenjualanSize = lPenjualan.getSize();
        Desktop.add(lPenjualan);
        lPenjualan.show();
        lPenjualan.setLocation((desktopSize.width - lPenjualanSize.width)/2, (desktopSize.height - lPenjualanSize.height)/2);
    }//GEN-LAST:event_btnlpenjualanActionPerformed

    private void btnlreturbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlreturbeliActionPerformed
         MenuUtama mUtama = new MenuUtama();
        LaporanReturPembelian lReturPembelian = new LaporanReturPembelian();
        Dimension desktopSize = Desktop.getSize();
        Dimension lReturPembelianSize = lReturPembelian.getSize();
        Desktop.add(lReturPembelian);
        lReturPembelian.show();
        lReturPembelian.setLocation((desktopSize.width - lReturPembelianSize.width)/2, (desktopSize.height - lReturPembelianSize.height)/2);
    }//GEN-LAST:event_btnlreturbeliActionPerformed

    private void btnlreturjualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlreturjualActionPerformed
        MenuUtama mUtama = new MenuUtama();
        LaporanReturPenjualan lReturPenjualan = new LaporanReturPenjualan();
        Dimension desktopSize = Desktop.getSize();
        Dimension lReturPenjualanSize = lReturPenjualan.getSize();
        Desktop.add(lReturPenjualan);
        lReturPenjualan.show();
        lReturPenjualan.setLocation((desktopSize.width - lReturPenjualanSize.width)/2, (desktopSize.height - lReturPenjualanSize.height)/2);
    }//GEN-LAST:event_btnlreturjualActionPerformed

    private void btnlkeuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlkeuanganActionPerformed
          MenuUtama mUtama = new MenuUtama();
        LaporanKeuangan lKeuangan = new LaporanKeuangan();
        Dimension desktopSize = Desktop.getSize();
        Dimension lKeuanganSize = lKeuangan.getSize();
        Desktop.add(lKeuangan);
        lKeuangan.show();
        lKeuangan.setLocation((desktopSize.width - lKeuanganSize.width)/2, (desktopSize.height - lKeuanganSize.height)/2);
    }//GEN-LAST:event_btnlkeuanganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuUtama().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JLabel TXTkodeuser;
    private javax.swing.JLabel TXTnamauser;
    private javax.swing.JLabel TXTstatususer;
    private javax.swing.JMenuItem btnbarang;
    private javax.swing.JMenuItem btnbyrutang;
    private javax.swing.JMenuItem btncustomer;
    private javax.swing.JMenuItem btnexit;
    private javax.swing.JMenuItem btnlkeuangan;
    private javax.swing.JMenuItem btnlogoff;
    private javax.swing.JMenuItem btnlpembelian;
    private javax.swing.JMenuItem btnlpenjualan;
    private javax.swing.JMenuItem btnlreturbeli;
    private javax.swing.JMenuItem btnlreturjual;
    private javax.swing.JMenuItem btnperkiraan;
    private javax.swing.JMenuItem btnprofil;
    private javax.swing.JMenuItem btnreturbeli;
    private javax.swing.JMenuItem btnreturjual;
    private javax.swing.JMenuItem btnsupplier;
    private javax.swing.JMenuItem btntpembelian;
    private javax.swing.JMenuItem btntpenjualan;
    private javax.swing.JMenuItem btntrmpiutang;
    private javax.swing.JMenuItem btnuser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

}
