
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import koneksi.conn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class TransaksiTerimaPiutang extends javax.swing.JInternalFrame {

    String TXTkode;

    /**
     * Creates new form TransaksiPenjualan
     */

    
    public TransaksiTerimaPiutang() {//CONSTRUCTOR

        initComponents();
        tampilfakturutang();
        nomorotomatis();
        infoutang();
    }
    
    
    public void nomorotomatis(){
        Date date = new Date();
        dtptanggal.setDate(date);
        try{
            Connection c = conn.getKoneksi();
            Statement s = c.createStatement();
            String sql = "select * from TBLTerimaPiutang where Nomor_Terima in(select max(Nomor_Terima) from TBLTerimaPiutang)";
            ResultSet res = s.executeQuery(sql);
            SimpleDateFormat sdf = new SimpleDateFormat("yyMMdd");
            if(res.next()){
                String fj = res.getString("nomor_terima").substring(2, 8);
                String dtp = sdf.format(date);
                if(fj.equals(dtp)){
                    int faktur = Integer.parseInt(res.getString("nomor_terima").substring(2, 10))+1;
                    lblnomor.setText(Integer.toString(faktur));
                    lblnomor.setText("TR"+lblnomor.getText());         
                }else{
                    lblnomor.setText("TR"+dtp+"01");
                }
            }else{
                lblnomor.setText("TR"+sdf.format(date)+"01");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, e);
        }  
    }
    
    public void tampilfakturutang(){
        listfaktur.removeAll();
         try{
            DefaultListModel listModel = new DefaultListModel();
            Connection c = conn.getKoneksi();
            Statement s = c.createStatement();
            String sql = "select * from TBLpenjualan where Status_Jual='BELUM LUNAS'";
            ResultSet res = s.executeQuery(sql);
            listModel.clear();
            while(res.next()){
                
                listModel.addElement(res.getString("faktur_jual").toUpperCase());
                listfaktur.setModel(listModel);
            }
         }catch(SQLException e){
             JOptionPane.showMessageDialog(rootPane, e);
         }       
    }
    
    public void infoutang(){
        if(listfaktur.getModel().getSize() == 0){
            JOptionPane.showMessageDialog(rootPane, "SEMUA UTANG SUDAH LUNAS");
        }
    }
    
    public void kosongkan(){
        lbltgljual.setText("");
        lblkodecustomer.setText("");
        lblnamacustomer.setText("");
        lbltotalharga.setText("");
        lblcarajual.setText("");
        lblsisapiutang.setText("");
        lbljatuhtempo.setText("");
        txtdibayar.setText("");
        txtjumlahterima.setText("");
        txtdibayar.setText("");
        DefaultTableModel model = (DefaultTableModel)dgv.getModel();
        while (model.getRowCount() > 0){
            for (int i = 0; i < model.getRowCount(); ++i){
                model.removeRow(i);
            }
        }
    }
         
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dtptanggal = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbltgljual = new javax.swing.JLabel();
        lblnomor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listfaktur = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        lblkodecustomer = new javax.swing.JLabel();
        lblnamacustomer = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dgv = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnsimpan = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        btntutup = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbltotalharga = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblsisapiutang = new javax.swing.JLabel();
        lbljatuhtempo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblcarajual = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtjumlahterima = new javax.swing.JTextField();
        txtdibayar = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(952, 500));

        jLabel1.setText("No Faktur Jual");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 20));

        jLabel2.setText("Tanggal Jual");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 20));

        dtptanggal.setDateFormatString("dd/MM/yyyy");
        dtptanggal.setPreferredSize(new java.awt.Dimension(100, 20));

        jLabel3.setText("Tanggal Terima");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 20));

        jLabel4.setText("Nomor Terima");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 20));

        jLabel5.setText("Nama Customer");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 20));

        lbltgljual.setPreferredSize(new java.awt.Dimension(100, 20));

        lblnomor.setPreferredSize(new java.awt.Dimension(100, 20));

        listfaktur.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listfakturValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listfaktur);

        jLabel6.setText("Kode Customer");
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 20));

        lblkodecustomer.setPreferredSize(new java.awt.Dimension(100, 20));

        lblnamacustomer.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dtptanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(lblnomor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblkodecustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbltgljual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblnamacustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtptanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbltgljual, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblnomor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblkodecustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblnamacustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        dgv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Harga", "Jumlah", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dgv.setEditingColumn(0);
        dgv.setEditingRow(0);
        dgv.setPreferredSize(new java.awt.Dimension(648, 235));
        dgv.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(dgv);

        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/TransaksiPembelian/btnsimpan.Image.png"))); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsimpan.setPreferredSize(new java.awt.Dimension(65, 73));
        btnsimpan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/TransaksiPembelian/btnbatal.Image.png"))); // NOI18N
        btnbatal.setText("Batal");
        btnbatal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbatal.setPreferredSize(new java.awt.Dimension(65, 73));
        btnbatal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        btntutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/TransaksiPembelian/btntutup.Image.png"))); // NOI18N
        btntutup.setText("Tutup");
        btntutup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btntutup.setPreferredSize(new java.awt.Dimension(65, 73));
        btntutup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btntutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntutupActionPerformed(evt);
            }
        });

        jLabel7.setText("Total Harga");
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 20));

        jLabel8.setText("Dibayar (Awal)");
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 20));

        lbltotalharga.setPreferredSize(new java.awt.Dimension(100, 20));

        jLabel10.setText("Sisa (Piutang)");
        jLabel10.setPreferredSize(new java.awt.Dimension(100, 20));

        lblsisapiutang.setPreferredSize(new java.awt.Dimension(100, 20));

        lbljatuhtempo.setPreferredSize(new java.awt.Dimension(100, 20));

        jLabel9.setText("Cara Jual");
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 20));

        lblcarajual.setPreferredSize(new java.awt.Dimension(100, 20));

        jLabel14.setText("Jatuh Tempo");
        jLabel14.setPreferredSize(new java.awt.Dimension(100, 20));

        jLabel11.setText("Jumlah Terima");
        jLabel11.setPreferredSize(new java.awt.Dimension(100, 20));

        txtjumlahterima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtjumlahterimaKeyPressed(evt);
            }
        });

        txtdibayar.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntutup, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltotalharga, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(lblcarajual, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtdibayar, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblsisapiutang, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbljatuhtempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(txtjumlahterima))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btntutup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblsisapiutang, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtjumlahterima))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbljatuhtempo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbltotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdibayar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcarajual, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntutupActionPerformed
        this.dispose();
    }//GEN-LAST:event_btntutupActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        
        kosongkan();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        if (txtjumlahterima.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Transaksi Belum Lengkap");
        }else{
            double sisautang = 0;
            if(Integer.parseInt(txtjumlahterima.getText()) < Integer.parseInt(lblsisapiutang.getText())){
                sisautang = Double.parseDouble(lblsisapiutang.getText()) - Double.parseDouble(txtjumlahterima.getText());
            }else if(Integer.parseInt(txtjumlahterima.getText()) >= Integer.parseInt(lblsisapiutang.getText())){
                sisautang = 0;
            }

        try{
            Connection c = conn.getKoneksi();
            Statement s = c.createStatement();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date dtp = dtptanggal.getDate();
            Timestamp dtptgl = new Timestamp(sdf.parse(sdf.format(dtp)).getTime());

            Date jatuh = sdf.parse(lbljatuhtempo.getText());
            Timestamp jatuhtempo = new Timestamp (sdf.parse(sdf.format(jatuh)).getTime());

                String simpan1  = "insert into tblterimapiutang values(?,?,?,?,?,?)";
                    PreparedStatement ps = c.prepareStatement(simpan1);
                    ps.setString(1, lblnomor.getText());
                    ps.setTimestamp(2, dtptgl);
                    ps.setString(3, listfaktur.getSelectedValue());
                    ps.setString(4, txtjumlahterima.getText());
                    ps.setDouble(5, sisautang);
                    ps.setString(6, TXTkode);
                    ps.executeUpdate();
                    
                    String simpanjurnal1  = "insert into tbljurnal values(?,?,?,?,?,?)";
                    ps = c.prepareStatement(simpanjurnal1);
                    ps.setString(1, lblnomor.getText());
                    ps.setTimestamp(2, dtptgl);
                    ps.setString(3, "100");
                    ps.setString(4, "KAS BAYAR UTANG DARI "+lblnamacustomer.getText());
                    ps.setInt(5, Integer.parseInt(txtjumlahterima.getText()));
                    ps.setInt(6, 0);

                    ps.executeUpdate();
                    
                    String simpanjurnal2  = "insert into tbljurnal values(?,?,?,?,?,?)";
                    ps = c.prepareStatement(simpanjurnal2);
                    ps.setString(1, lblnomor.getText());
                    ps.setTimestamp(2, dtptgl);
                    ps.setString(3, "101");
                    ps.setString(4, "PIUTANG "+lblnamacustomer.getText());
                    ps.setInt(5, 0);
                    ps.setInt(6, Integer.parseInt(txtjumlahterima.getText()));

                    ps.executeUpdate();
                    
                    String sql = "select * from tblpenjualan where faktur_jual='"+listfaktur.getSelectedValue()+"'";
                    ResultSet res = s.executeQuery(sql);
                    if(res.next()){
                        if(Integer.parseInt(txtjumlahterima.getText()) >= Integer.parseInt(lblsisapiutang.getText())){
                            String edit = "Update tblpenjualan set status_jual='LUNAS', sisa_piutang='0' where faktur_jual='"+listfaktur.getSelectedValue()+"'";
                            PreparedStatement st=c.prepareStatement(edit);
                            st.execute();
                        }else{
                        String edit1 = "update tblpenjualan set sisa_piutang='"+(Integer.parseInt(res.getString("sisa_piutang"))-Integer.parseInt(txtjumlahterima.getText()))+
                                "'where faktur_jual='"+listfaktur.getSelectedValue()+"'";
                        PreparedStatement st=c.prepareStatement(edit1);
                        st.execute();
                    }
                    }
            }catch(SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);
            } catch (ParseException ex) { 
                Logger.getLogger(TransaksiTerimaPiutang.class.getName()).log(Level.SEVERE, null, ex);
            }
            nomorotomatis();
            kosongkan();
            tampilfakturutang();
            infoutang();
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void txtjumlahterimaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjumlahterimaKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER){
            if(Integer.parseInt(txtjumlahterima.getText()) < Integer.parseInt(lblsisapiutang.getText())){
                JOptionPane.showMessageDialog(rootPane, "Sisa Piutang "+(Integer.parseInt(lblsisapiutang.getText()) - Integer.parseInt(txtjumlahterima.getText())));
                btnsimpan.requestFocus();
            }else if(Integer.parseInt(txtjumlahterima.getText()) == Integer.parseInt(lblsisapiutang.getText())){
                JOptionPane.showMessageDialog(rootPane, "Piutang Lunas");
                btnsimpan.requestFocus();
            }else if(Integer.parseInt(txtjumlahterima.getText()) > Integer.parseInt(lblsisapiutang.getText())){
                 JOptionPane.showMessageDialog(rootPane, "Piutang Lunas, Uang Kembali "+(Integer.parseInt(txtjumlahterima.getText()) - Integer.parseInt(lblsisapiutang.getText())));
                 btnsimpan.requestFocus();
            }
        }
    }//GEN-LAST:event_txtjumlahterimaKeyPressed

    private void listfakturValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listfakturValueChanged
        kosongkan();
        try{
            DefaultTableModel data = (DefaultTableModel) dgv.getModel();
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment( JLabel.CENTER );
            dgv.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
            SimpleDateFormat sdfinput = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat sdfoutput = new SimpleDateFormat("dd/MM/yyyy");
              Connection c = conn.getKoneksi();
              Statement s = c.createStatement();
              String sql = "select * from tblpenjualan where faktur_jual= '"+listfaktur.getSelectedValue()+"'";
              ResultSet res = s.executeQuery(sql);
              if(res.next()){
                  Date jatuh = sdfinput.parse(res.getString("jth_tempo_jual"));
                  Date tgljual = sdfinput.parse(res.getString("tgl_jual"));
                  lbltgljual.setText(sdfoutput.format(tgljual));
                  lblkodecustomer.setText(res.getString("kode_customer"));
                  lbltotalharga.setText(res.getString("total_jual"));
                  txtdibayar.setText(res.getString("bayar_jual"));
                  lblcarajual.setText(res.getString("cara_jual"));
                  lblsisapiutang.setText(res.getString("sisa_piutang"));
                  lbljatuhtempo.setText(sdfoutput.format(jatuh));
                  txtjumlahterima.setText(lblsisapiutang.getText());
                  
                  String customer = "select * from tblcustomer where KODE_customer='"+ lblkodecustomer.getText()+"'";
                  res = s.executeQuery(customer);
                  if(res.next()){
                      lblnamacustomer.setText(res.getString("nama_customer"));
                  }
              
        
        
        String datadgv = "Select tbldetailJual.kode_barang as [Kode Barang],tblbarang.Nama_barang as [Nama Barang],"
                + "tbldetailJual.harga_JL as [Harga],qty_Jual as [Jumlah],subtotal_Jual as [Total] from tbldetailJual,"
                + "tblbarang where tbldetailJual.kode_barang=tblbarang.kode_barang and tbldetailJual.Faktur_Jual='"
                    +listfaktur.getSelectedValue()+"'";
        res = s.executeQuery(datadgv);
        while(res.next()){
             
                String kolom1 = res.getString("Kode Barang");
                String kolom2 = res.getString("Nama Barang");
                String kolom3 = res.getString("harga");
                String kolom4 = res.getString("jumlah");
                String kolom5 = res.getString("total");
                
                String kolom[] = {kolom1, kolom2, kolom3, kolom4, kolom5};
                data.addRow(kolom);
                
        }   
            }
              
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);
                
            } catch (ParseException ex) { 
            Logger.getLogger(TransaksiTerimaPiutang.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_listfakturValueChanged

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntutup;
    private javax.swing.JTable dgv;
    private com.toedter.calendar.JDateChooser dtptanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblcarajual;
    private javax.swing.JLabel lbljatuhtempo;
    private javax.swing.JLabel lblkodecustomer;
    private javax.swing.JLabel lblnamacustomer;
    private javax.swing.JLabel lblnomor;
    private javax.swing.JLabel lblsisapiutang;
    private javax.swing.JLabel lbltgljual;
    private javax.swing.JLabel lbltotalharga;
    private javax.swing.JList<String> listfaktur;
    private javax.swing.JLabel txtdibayar;
    private javax.swing.JTextField txtjumlahterima;
    // End of variables declaration//GEN-END:variables

}
